# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/germaniumsculk/android_kernel_xiaomi_southwest-4.19
          kernel-dir: xiaomi/lavender
          continue-on-error: true
          kernel-branch: main-ksu-next
          config: lavender-full_defconfig
          arch: arm64
          aosp-clang: false
          aosp-gcc: true
          other-clang-url: https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240605-release/Clang-19.0.0git-20240605.tar.gz
          android-version: 12
          disable-lto: true
          anykernel3: false
          
      # PACKAGE MANUALLY (Since we have Image.gz-dtb)
      - name: Package Kernel
        run: |
          echo "Cloning AnyKernel3..."
          git clone https://github.com/osm0sis/AnyKernel3
          
          echo "Copying Kernel Image..."
          # Move the compiled kernel to AnyKernel3 folder
          cp kernel/xiaomi/lavender/out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          
          cd AnyKernel3
          
          # Configure for Lavender
          sed -i 's/device.name1=maguro/device.name1=lavender/g' anykernel.sh
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' anykernel.sh
          
          # Remove dtbo flashing commands (since we don't have one)
          sed -i '/dtbo.img/d' anykernel.sh
          
          # Zip it up
          zip -r9 ../AnyKernel3-Lavender.zip *

      # UPLOAD ZIP
      - name: Upload Kernel Zip
        uses: actions/upload-artifact@v4
        with:
          name: Lavender-Kernel-Zip
          path: AnyKernel3-Lavender.zip
